DROP DATABASE IF EXISTS business_db;
CREATE DATABASE business_db;
USE business_db;

DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS departments;

CREATE TABLE employee(
id INTEGER (12) AUTO_INCREMENT NOT NULL PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT,
manager_id INT
);

CREATE TABLE role(
id INTEGER (12) AUTO_INCREMENT NOT NULL PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL(8,0),
department_id INT
);

CREATE TABLE departments(
id INTEGER (12) AUTO_INCREMENT NOT NULL,
department VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);
